#include "alarm.h"

void en_alarm(){
	TIMER_mWriteReg(XPAR_TIMER_0_S00_AXI_BASEADDR, TIMER_S00_AXI_SLV_REG7_OFFSET, 0x0001);
}

void cancel_alarm(){
	TIMER_mWriteReg(XPAR_TIMER_0_S00_AXI_BASEADDR, TIMER_S00_AXI_SLV_REG7_OFFSET, 0x0000);
}

void en_alarm_min(){
	u8 min = TIMER_mReadReg(XPAR_TIMER_0_S00_AXI_BASEADDR, TIMER_S00_AXI_SLV_REG8_OFFSET);
	if (min < 59){
		TIMER_mWriteReg(XPAR_TIMER_0_S00_AXI_BASEADDR, TIMER_S00_AXI_SLV_REG8_OFFSET, min + 1);
	}
	else
		TIMER_mWriteReg(XPAR_TIMER_0_S00_AXI_BASEADDR, TIMER_S00_AXI_SLV_REG8_OFFSET, 0x0000);
}

void en_alarm_hor(){
	u8 hor = TIMER_mReadReg(XPAR_TIMER_0_S00_AXI_BASEADDR, TIMER_S00_AXI_SLV_REG9_OFFSET);
	if (hor < 59){
		TIMER_mWriteReg(XPAR_TIMER_0_S00_AXI_BASEADDR, TIMER_S00_AXI_SLV_REG9_OFFSET, hor + 1);
	}
	else
		TIMER_mWriteReg(XPAR_TIMER_0_S00_AXI_BASEADDR, TIMER_S00_AXI_SLV_REG9_OFFSET, 0x0000);
}
