#include "stopwatch.h"
#include "xparameters.h"
#include "xil_io.h"
#include "stdio.h"


void sw_on(){
	STOPWATCH_mWriteReg(XPAR_STOPWATCH_0_S00_AXI_BASEADDR, STOPWATCH_S00_AXI_SLV_REG0_OFFSET, 0x0001);
}

void sw_stp(){
	STOPWATCH_mWriteReg(XPAR_STOPWATCH_0_S00_AXI_BASEADDR, STOPWATCH_S00_AXI_SLV_REG0_OFFSET, 0x0000);
}

void sw_clr(){
	STOPWATCH_mWriteReg(XPAR_STOPWATCH_0_S00_AXI_BASEADDR, STOPWATCH_S00_AXI_SLV_REG0_OFFSET, 0x0002);
	STOPWATCH_mWriteReg(XPAR_STOPWATCH_0_S00_AXI_BASEADDR, STOPWATCH_S00_AXI_SLV_REG0_OFFSET, 0x0000);
}

u8 sw_sec_out(){
	u8 sec = STOPWATCH_mReadReg(XPAR_STOPWATCH_0_S00_AXI_BASEADDR, STOPWATCH_S00_AXI_SLV_REG1_OFFSET);
	return sec;
}

u8 sw_min_out(){
	u8 min = STOPWATCH_mReadReg(XPAR_STOPWATCH_0_S00_AXI_BASEADDR, STOPWATCH_S00_AXI_SLV_REG2_OFFSET);
	return min;
}

u8 sw_hor_out(){
	u8 hor = STOPWATCH_mReadReg(XPAR_STOPWATCH_0_S00_AXI_BASEADDR, STOPWATCH_S00_AXI_SLV_REG3_OFFSET);
	return hor;
}
