#include "timer_counter.h"

void en_in_min(){
	u8 min = COUNTER_mReadReg(XPAR_COUNTER_0_S00_AXI_BASEADDR, COUNTER_S00_AXI_SLV_REG1_OFFSET);
	if (min < 59){
	COUNTER_mWriteReg(XPAR_COUNTER_0_S00_AXI_BASEADDR, COUNTER_S00_AXI_SLV_REG1_OFFSET, min + 1);
	COUNTER_mWriteReg(XPAR_COUNTER_0_S00_AXI_BASEADDR, COUNTER_S00_AXI_SLV_REG0_OFFSET, 0x0001);
	COUNTER_mWriteReg(XPAR_COUNTER_0_S00_AXI_BASEADDR, COUNTER_S00_AXI_SLV_REG0_OFFSET, 0x0000);
	}
}

void de_in_min(){
	u8 min = COUNTER_mReadReg(XPAR_COUNTER_0_S00_AXI_BASEADDR, COUNTER_S00_AXI_SLV_REG1_OFFSET);
	if (min > 0){
	COUNTER_mWriteReg(XPAR_COUNTER_0_S00_AXI_BASEADDR, COUNTER_S00_AXI_SLV_REG1_OFFSET, min - 1);
	COUNTER_mWriteReg(XPAR_COUNTER_0_S00_AXI_BASEADDR, COUNTER_S00_AXI_SLV_REG0_OFFSET, 0x0001);
	COUNTER_mWriteReg(XPAR_COUNTER_0_S00_AXI_BASEADDR, COUNTER_S00_AXI_SLV_REG0_OFFSET, 0x0000);
	}
}

void str_timer(){
	COUNTER_mWriteReg(XPAR_COUNTER_0_S00_AXI_BASEADDR, COUNTER_S00_AXI_SLV_REG0_OFFSET, 0x0006);
}

void cancel_timer(){
	COUNTER_mWriteReg(XPAR_COUNTER_0_S00_AXI_BASEADDR, COUNTER_S00_AXI_SLV_REG1_OFFSET, 0x0000);
	COUNTER_mWriteReg(XPAR_COUNTER_0_S00_AXI_BASEADDR, COUNTER_S00_AXI_SLV_REG0_OFFSET, 0x0001);
	COUNTER_mWriteReg(XPAR_COUNTER_0_S00_AXI_BASEADDR, COUNTER_S00_AXI_SLV_REG0_OFFSET, 0x0000);
}

void dis_inter(){
	COUNTER_mWriteReg(XPAR_COUNTER_0_S00_AXI_BASEADDR, COUNTER_S00_AXI_SLV_REG1_OFFSET, 0x0000);
}
